<h1>Index</h1>
<hr />

<?php
    echo "<h3>Chegamos ao IndexController e disparamos a action index.</h3>";
    echo "Listando os dados: <br />";
    echo "<ul>";
    // echo "<pre>";
    // print_r($this->view->dados);
    // echo "</pre>";
    echo "<hr>";
    foreach($this->view->dados as $indice => $aluno) {
        echo "<li>".$aluno['matricula']." => ".$aluno['nome']."</li>";
    }
    echo "</ul>";
?>